---
- name: Reload systemctl daemon
  ansible.builtin.systemd:
    daemon_reexec: yes
  when: ansible_service_mgr == 'systemd'

- name: Restart zookeeper
  ansible.builtin.systemd:
    name: zookeeper-server
    state: restarted
